# Generated by Django 5.2.4 on 2025-08-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblregister',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.batch'),
        ),
    ]
