# Generated by Django 5.2.4 on 2025-08-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_tblregister_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='mylecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('video_info', models.TextField(null=True)),
                ('vlink', models.CharField(max_length=300, null=True)),
                ('posted_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
        migrations.CreateModel(
            name='mytask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('task_info', models.TextField(null=True)),
                ('taskfile', models.FileField(blank=True, null=True, upload_to='static/task/')),
                ('upload_task', models.FileField(blank=True, null=True, upload_to='static/submitted/')),
                ('posted_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('notes_info', models.TextField(null=True)),
                ('posted_date', models.DateField(null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.batch')),
            ],
        ),
    ]
