# Generated by Django 5.2.4 on 2025-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_mylecture_mytask_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notesfile',
            field=models.FileField(blank=True, null=True, upload_to='static/notes/'),
        ),
    ]
