# Generated by Django 5.2.4 on 2025-08-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_submittedtask_remove_mytask_upload_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submittedtask',
            old_name='titlle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='submittedtask',
            name='marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='submittedtask',
            name='tid',
            field=models.IntegerField(null=True),
        ),
    ]
